apiVersion: apps/v1
kind: Deployment
metadata:
  name: evoli-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ameniii/test_evoli
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: evoli-service 
spec: 
  selector: 
    app: nginx 
  ports: 
  - protocol: TCP 
    port: 3000 
    nodePort: 31000 
  type: NodePort 
